### ISSUE TITLE
卷积的反向传播

### ISSUE THREAD

**Issue by LIUHAO121** [hijkzzz/neural-network#10]
src/cuda/conv.cu 的第120行，计算height_col的公式是“int height_col = height + 2 * pad_h - kernel_h / stride_h + 1;”
为什么不是 “int height_col = (height + 2 * pad_h - kernel_h )/ stride_h + 1;” 是不是忘写了个括号呀

**Comment by hijkzzz** [comment]
是的，我test的时候没有测stride，所以没发现。老哥可以修复下然后 pull requests ?
