### ISSUE TITLE
Any plans for save model and real image inference?

### ISSUE THREAD

**Issue by qixuxiang** [hijkzzz/neural-network#4]
Thanks for your awesome code share!

Recently I compare some cuda and cpp mnist train tools from github, this repo is almost the fastest and most accurate one. With functions of  saving model and real 28*28 image inference, it is not only a great research tool but also a fast and accurate app.

**Comment by hijkzzz** [comment]
I am sorry that I wrote this project just for learning CUDA, so it is not perfect in many places. If you are interested, you can continue to improve, such as faster matrix multiplication, model saver and code refactoring.

**Comment by qixuxiang** [comment]
Thanks for your reply^_^

I will pay attention to your repo and learn CUDA from it. I am also happy to contribute to it.
