### ISSUE TITLE
Why am I getting "nvcc fatal : redefinition of argument 'optimize'"?

### ISSUE THREAD

**Issue by NicoNico6** [hijkzzz/neural-network#9]
Hi, thanks for your project. I am trying to learn cuda with the help of your code. When I tried to install and make this cuda project, I got the error "nvcc fatal : redefinition of argument 'optimize". It seems that it is a bug from nvcc? May you help me?

**Comment by hijkzzz** [comment]
It seems like that you should remove '-O2' in CMakeLists.txt.
I have fix it.
